Working network

In [ ]:
import numpy as np
import math

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in xrange(1000):

    # forward propagation
    l1 = nonlin(np.dot(X,syn0))
    
    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(X.T,l1_delta)

print "Output After Training:"
print syn0
print l1_error

Clean one layer network

In [ ]:
import numpy as np
import math

# sigmoid function
def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1],
                [1,0,1]])
    
# output dataset            
y = np.array([[0,0,1,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
W = np.random.randn(3, 1)

for iter in xrange(1000):

    # forward propagation
    A = np.dot(X,W)
    H = sigmoid(A)
    
    # how much did we miss?
    L = 0.5 * ( y - H ) ** 2
    
    dLdH = -1.0 * (y - H)
    
    dHdA = sigmoid(H, True)

    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    dLdA = dLdH * dHdA
    
    # xij = observation i, feature j
    # A1 = w1 * x11 + w2 * x12 + w3 * x13
    # A2 = w1 * x21 + w2 * x22 + w3 * x23
    # A3 = w1 * x31 + w2 * x32 + w3 * x33
    
    dAdW = X.T
    
    # 3 x 1 = 3 x n * n x 1
    dLdW = np.dot(dAdW, dLdA)
    # Weight i, observation j is updated by sum(j=1^n) (Xi * dLdA),
    # where j runs over all the observations
    # times the product of the other derivatives,
    # as we expect 
    
    # dA / dW = [[x11 x12 x13]
    #            [x21 x22 x23]
    #            ...
    #            [xn1 xn2 xn3]]
    # dLdA = [A1 A2 ... An]
    
    # update weights
    # w1 -= A1 * x11 + A2 * x21 + ... + An * xn1
    # w2 -= A1 * x12 + A2 * x22 + ... + An * xn2
    # w3 -= A1 * x13 + A2 * x23 + ... + An * xn3
    W -= dLdW

print "Output After Training:"
print W
print H

Two layer network

In [ ]:
# Sigmoid function
def sigmoid(x,deriv=False):
    return 1/(1+np.exp(-x))



In [ ]:
#### import numpy as np
import math

# sigmoid function
def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))



# input dataset
X = np.array([[0,0,1]])
    
# output dataset            
y = np.array([[1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
V = np.random.randn(3, 4)
W = np.random.randn(4, 1)

for i in xrange(1000):

    # forward propagation
    A1 = np.dot(X,V)
    A2 = sigmoid(A1)
    
    B1 = np.dot(A2,W)
    B2 = sigmoid(B1)
    
    L = 0.5 * ( y - B2 ) ** 2
    
    # n x 1
    dLdB2 = -1.0 * (y - B2)

    # n x 1
    dB2dB1 = sigmoid(B2, deriv=True) 

    # n x 1 = n x 1 * n x 1
    dLdB1 = dLdB2 * dB2dB1
    
    # 4 x n
    dB1dW = A2.T
    
    # 4 x 1
    dB1dA2 = W
    
    # n x 4
    dA2dA1 = sigmoid(A2, deriv=True)

    # n x 1 = n x 4 * 4 x 1 
    dB1dA1 = np.dot(dA2dA1, dB1dA2)

    # 3 x n
    dA1dV = X.T
    
    # n x 1 = n x 1 * n x 1
    dLdA1 = dB1dA1 * dLdB1 
    
    # 3 x 1 = 3 x n * n x 1
    # dLdA1 has to be n x 4
    dLdV = np.dot(dA1dV, dLdA1) 
    
    W -= 0.5 * dLdW
    
    V -= 0.5 * dLdV  

print "Output After Training:"
print np.mean(L)
print B2

A2

# Code for deck

In [5]:
# Initialize the X and y arrays
x1 = 0
x2 = 0
x3 = 1
y1 = 1

import numpy as np
X = np.array([[x1,x2,x3]])
y = np.array([[y1]]).T

# Initialize `V`
V = np.random.randn(3, 4)

# Multiply `X` by `V`
A = np.dot(X,V)

In [ ]:
B = sigmoid(A)

# Two layer

In [ ]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)
	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
V = 2*np.random.random((3,4)) - 1
W = 2*np.random.random((4,1)) - 1

for j in xrange(60000):

	# Feed forward through layers 0, 1, and 2
    A1 = np.dot(X,V)
    A2 = nonlin(A1)
    B1 = np.dot(A2,W)
    P = nonlin(B1)

    # how much did we miss the target value?
    B2_error = y - P
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(B2_error)))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    B2_delta = B2_error*nonlin(P,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    A2_error = B2_delta.dot(W.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    A1_delta = A2_error * nonlin(A2,deriv=True)

    W += A2.T.dot(B2_delta)
    V += X.T.dot(A1_delta)

In [ ]:
dLdV = dAdV.dot(dLdP*dPdC.dot(dCdB) * dBdA)

In [ ]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)
	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1],
             [1,1,0],
             [0,0,0],
             [0,1,0]])
                
y = np.array([[0],
              [0],
              [1],
              [1],
              [1],
              [1],
             [1]])

np.random.seed(1)

# randomly initialize our weights with mean 0
V = np.random.randn(3, 4)
W = np.random.randn(4, 1)

for j in xrange(60000):

	# Feed forward through layers 0, 1, and 2
    A = np.dot(X,V)
    B = nonlin(A)
    C = np.dot(B,W)
    P = nonlin(C)

    # how much did we miss the target value?
    L = 0.5 * (y - P) ** 2
    
    if ( j % 10000) == 0:
        print "Error:" + str(np.mean(np.abs(L)))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    dLdP = -1.0 * (y-P)
    
    dPdC = nonlin(P,deriv=True)

    dLdC = dLdP*dPdC

    dCdW = B.T
    
    dLdW = dCdW.dot(dLdC)
    
    dCdB = W.T
    
    dLdB = dLdC.dot(dCdB)
    
    dBdA = nonlin(B,deriv=True)
    
    dLdA = dLdB * dBdA
    
    dAdV = X.T
    
    dLdV = dAdV.dot(dLdA)

    # W (4 x 1) = A2.T (4 x n) * B2_delta (n x 1)
    W -= dLdW 
    
    # V (3 x 4) = X.T (3 x n) * A1_delta (n x 4)
    V -= dLdV

In [ ]:
dCdW = B.T

In [ ]:
def sigmoid(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)
	return 1/(1+np.exp(-x))

X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1],
             [1,1,0],
             [0,0,0],
             [0,1,0]])
                
y = np.array([[0],
              [0],
              [1],
              [1],
              [1],
              [1],
             [1]])
V = np.random.randn(3, 4)
W = np.random.randn(4, 1)
for j in range(60000):
    A = np.dot(X,V)
    B = nonlin(A)
    C = np.dot(B,W)
    P = nonlin(C)
    L = 0.5 * (y - P) ** 2
    if ( j % 10000) == 0:
        print "Error:" + str(np.mean(np.abs(L)))
    dLdP = -1.0 * (y-P)
    dPdC = sigmoid(C) * (1-sigmoid(C))
    dLdC = dLdP * dPdC
    dCdW = B.T
    dLdW = np.dot(dCdW, dLdC)
    dCdB = W.T
    dLdB = dLdC * dCdB
    dBdA = sigmoid(A) * (1-sigmoid(A))
    dLdA = dLdB * dBdA
    dAdV = X.T
    dLdV = np.dot(dAdV, dLdA)
    W -= dLdW
    V -= dLdV

In [8]:
import numpy as np
import random
np.random.seed(1)
randX = np.random.choice(range(1,9), size=8, replace=False)
mapping_dict = {1:[0,0,0],
               2:[0,0,1],
               3:[0,1,0],
               4:[0,1,1],
               5:[1,0,0],
               6:[1,0,1],
               7:[1,1,0],
               8:[1,1,1]}
X = []
for r in randX:
    X.append(mapping_dict[r])


y = []
randy = np.random.choice(range(1,9), size=8, replace=False)
for el in randy:
    if el % 2 == 0:
        y.append([0])
    else:
        y.append([1])


X = np.array(X)
y = np.array(y)

print "X: %s" % str(X)
print "y: %s" % str(y)

X: [[1 1 1]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [0 0 0]
 [1 0 0]
 [0 1 1]
 [1 0 1]]
y: [[1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]]


In [ ]:
def sigmoid(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)
	return 1/(1+np.exp(-x))

V = np.random.randn(3, 4)
W = np.random.randn(4, 1)
for j in range(60000):
    A = np.dot(X,V)
    B = nonlin(A)
    C = np.dot(B,W)
    P = nonlin(C)
    L = 0.5 * (y - P) ** 2
    if ( j % 10000) == 0:
        print "Error:" + str(np.mean(np.abs(L)))
    dLdP = -1.0 * (y-P)
    dPdC = sigmoid(C) * (1-sigmoid(C))
    dLdC = dLdP * dPdC
    dCdW = B.T
    dLdW = np.dot(dCdW, dLdC)
    dCdB = W.T
    dLdB = dLdC * dCdB
    dBdA = sigmoid(A) * (1-sigmoid(A))
    dLdA = dLdB * dBdA
    dAdV = X.T
    dLdV = np.dot(dAdV, dLdA)
    W -= dLdW
    V -= dLdV

Code changes:

In [ ]:
def sigmoid(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)
	return 1/(1+np.exp(-x))

In [ ]:
def learn(X, y, num_hidden, iterations):
    np.random.seed(2)
    V = np.random.randn(X.shape[0], num_hidden)
    W = np.random.randn(num_hidden, y.shape[0])
    for j in range(60000):
        A = np.dot(X,V)
        B = sigmoid(A)
        C = np.dot(B,W)
        P = sigmoid(C)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdC = sigmoid(C) * (1-sigmoid(C))
        dLdC = dLdP * dPdC
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = dLdC * dCdB
        dBdA = sigmoid(A) * (1-sigmoid(A))
        dLdA = dLdB * dBdA
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        W -= dLdW
        V -= dLdV
    return V, W
        
def predict(X_new, V, W):
    A = np.dot(X_new,V)
    B = sigmoid(A)
    C = np.dot(B,W)
    P = sigmoid(C)
    return P

X_new = [[1, 1, 1], [0, 1, 0]]
V, W = learn(X, y)
print "V: %s" % str(V)
print "W: %s" % str(W)
np.set_printoptions(suppress=True)
P = predict(X_new, V, W)
P

In [ ]:
def learn_simple_net(X, y):
    W = np.random.randn(3, 1)
    for i in range(50001):
        A = np.dot(X, W)
        P = sigmoid(A)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y - P)
        dPdA = sigmoid(A) * (1.0 - sigmoid(A))
        dLdA = dLdP * dPdA
        dAdW = X.T
        dLdW = np.dot(dAdW, dLdA)
        W -= 0.5 * dLdW
    return W

def predict_simple_net(X_new, W):
    A = np.dot(X_new, W)
    P = sigmoid(A)
    return P

In [ ]:
import numpy as np
def generate_X_y():
    np.random.seed(1)
    randX = np.random.choice(range(1,9), size=8, replace=False)
    mapping_dict = {1:[0,0,0],
                   2:[0,0,1],
                   3:[0,1,0],
                   4:[0,1,1],
                   5:[1,0,0],
                   6:[1,0,1],
                   7:[1,1,0],
                   8:[1,1,1]}
    X = []
    for r in randX:
        X.append(mapping_dict[r])

    y = []
    randy = np.random.choice(range(1,9), size=8, replace=False)
    for el in randy:
        if el % 2 == 0:
            y.append([0])
        else:
            y.append([1])

    X = np.array(X)
    y = np.array(y)
    return X, y

# No bias

In [ ]:
X, y = generate_X_y()
W = learn_simple_net(X, y)

In [ ]:
X_xor = np.array([[0,0], [0,1], [1,0], [1,1]])
y_xor = np.array([[1], [0], [0], [1]])

In [ ]:
def learn_simple_net_no_bias(X, y, num_features):
    W = np.random.randn(num_features, 1)
    for i in range(50001):
        A = np.dot(X, W)
        P = sigmoid(A)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y - P)
        dPdA = sigmoid(A) * (1.0 - sigmoid(A))
        dLdA = dLdP * dPdA
        dAdW = X.T
        dLdW = np.dot(dAdW, dLdA)
        W -= 0.5 * dLdW
    return W

def predict_simple_net_no_bias(X_new, W):
    A = np.dot(X_new, W)
    P = sigmoid(A)
    return P

In [ ]:
W = learn_simple_net_no_bias(X_xor, y_xor, 2)
print W
predict_simple_net_no_bias(X_xor, W)

In [ ]:
np.random.seed(1)
def learn_complex_net(X, y):
    np.random.seed(1)
    V = np.random.randn(X.shape[1], 3)
    W = np.random.randn(3, 1)
    for j in range(10000):
        A = np.dot(X,V)
        B = sigmoid(A)
        C = np.dot(B,W)
        P = sigmoid(C)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdC = sigmoid(C) * (1-sigmoid(C))
        dLdC = dLdP * dPdC
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = dLdC * dCdB
        dBdA = sigmoid(A) * (1-sigmoid(A))
        dLdA = dLdB * dBdA
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        W -= dLdW
        V -= dLdV
    return V, W

V, W = learn_complex_net(X_xor, y_xor)

In [ ]:
def predict_complex_net(X_new, V, W):
    A = np.dot(X_new,V)
    B = sigmoid(A)
    C = np.dot(B,W)
    P = sigmoid(C)
    return P

predict_complex_net(X_xor, V, W)

In [ ]:
print "V: " + str(np.around(V, 2))
print "W: " + str(np.around(W, 2))
B = sigmoid(np.dot(X_xor, V))
print "B: " + str(np.around(B, 2))
C = np.dot(B, W)
print "C: " + str(np.around(C, 2))
P = sigmoid(C)
print "P: " + str(np.around(P, 2))

In [ ]:
X_xor

In [ ]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])

In [ ]:
X

In [ ]:
y = [[1], [0], [0], [1]]

In [ ]:
def learn_simple_net(X, y, num_features):
    W = np.random.randn(num_features, 1)
    for i in range(50001):
        A = np.dot(X, W)
        P = sigmoid(A)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y - P)
        dPdA = sigmoid(A) * (1.0 - sigmoid(A))
        dLdA = dLdP * dPdA
        dAdW = X.T
        dLdW = np.dot(dAdW, dLdA)
        W -= 0.5 * dLdW
    return W

W = learn_simple_net(X, y, 2)
X_new = X 
predict_simple_net(X_new, W)

In [ ]:
def learn_complex_net(X, y, num_features):
    np.random.seed(2)
    V = np.random.randn(num_features, 3)
    W = np.random.randn(3, 1)
    for j in range(60000):
        A = np.dot(X,V)
        B = sigmoid(A)
        C = np.dot(B,W)
        P = sigmoid(C)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdC = sigmoid(C) * (1-sigmoid(C))
        dLdC = dLdP * dPdC
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = dLdC * dCdB
        dBdA = sigmoid(A) * (1-sigmoid(A))
        dLdA = dLdB * dBdA
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        W -= dLdW
        V -= dLdV
    return V, W

V, W = learn_complex_net(X, y, 2)

In [ ]:
X_new = X

def predict_complex_net(X_new, V, W):
    A = np.dot(X_new,V)
    B = sigmoid(A)
    C = np.dot(B,W)
    P = sigmoid(C)
    return P

predict_complex_net(X_new, V, W)

# Add bias

In [ ]:
X

In [ ]:
X

In [ ]:
def learn_simple_net(X, y, num_features, num_obs):
    W = np.random.randn(num_features, 1)
    bias_init = np.random.normal(0, 1)
    A_bias = np.full((num_obs, 1), bias_init)
    for i in range(50001):
        A = np.dot(X, W)
        C = A + A_bias
        P = sigmoid(C)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y - P)
        dPdC = sigmoid(C) * (1.0 - sigmoid(C))
        dLdC = dLdP * dPdC
        dCdA_bias = 1
        dLdA_bias = dLdC * dCdA_bias
        dCdA = 1
        dLdA = dLdC * dCdA        
        dAdW = X.T
        dLdW = np.dot(dAdW, dLdA)
        A_bias -= 0.5 * np.full((num_obs, 1), np.mean(dLdA_bias))
        W -= 0.5 * dLdW
    return W, B

W, B = learn_simple_net(X, y, 2, 4)

In [ ]:
W

In [ ]:
B

In [ ]:
A = np.dot(X_new, W)
A + B

In [ ]:
def predict_simple_net(X_new, W, A_bias):
    A = np.dot(X_new, W)
    C = A + A_bias
    P = sigmoid(C)
    return P

predict_simple_net(X_new, W, B)

# Add bias to complex net

In [ ]:
def learn_complex_net(X, y, num_features, num_obs):
    np.random.seed(2)
    V = np.random.randn(num_features, 3)
    A_bias_init = np.random.normal(0, 1) 
    A_bias = np.full((num_obs, 1), A_bias_init)
    W = np.random.randn(3, 1)
    C_bias_init = np.random.normal(0, 1)
    C_bias = np.full((num_obs, 1), C_bias_init)
    for j in range(60000):
        A = np.dot(X,V)
        A_final = A + A_bias
        B = sigmoid(A_final)
        C = np.dot(B,W)
        C_final = C + C_bias
        P = sigmoid(C_final)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdC_final = sigmoid(C_final) * (1-sigmoid(C_final))
        dLdC_final = dLdP * dPdC_final
        dC_finaldC = 1
        dC_finalC_bias = 1
        dLdC_bias = dLdC_final * dC_finalC_bias
        dLdC = dLdC_final * dC_finaldC 
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = dLdC * dCdB
        dBdA_final = sigmoid(A_final) * (1-sigmoid(A_final))
        dLdA_final = dLdB * dBdA_final
        dA_finaldA = 1
        dA_finaldA_bias = 1
        dLdA_bias = dLdA_final * dA_finaldA_bias 
        dLdA = dLdA_final * dA_finaldA 
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        C_bias -= 0.5 * np.full((num_obs, 1), np.mean(dLdC_bias)) 
        A_bias -= 0.5 * np.full((num_obs, 1), np.mean(dLdA_bias)) 
        W -= 0.5 * dLdW
        V -= 0.5 * dLdV
    return V, W, np.mean(C_bias), np.mean(A_bias)

# V, W, C_bias, A_bias = learn_complex_net(X, y, 2, 4)

In [ ]:
A 

In [ ]:
X

In [ ]:
def predict_complex_net(X_new, V, W, C_bias, A_bias):
    A = np.dot(X_new,V)
    A_final = A + A_bias
    B = sigmoid(A_final)
    C = np.dot(B,W)
    C_final = C + C_bias
    P = sigmoid(C_final)
    return P

predict_complex_net(X_new, V, W, C_bias, A_bias)

Testing with complex data

In [ ]:
X, y = generate_X_y()

In [ ]:
V, W, C_bias, A_bias = learn_complex_net(X, y, 3, 8)
X_new = X
predict_complex_net(X_new, V, W, C_bias, A_bias)

In [ ]:
y

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
X

In [ ]:

# Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

In [ ]:
X_new.shape

In [ ]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])

In [ ]:
y = [[1], [0], [0], [1]]

In [6]:
def learn(X, y, num_hidden, num_iterations): 
    V = np.random.randn(X.shape[0], num_hidden)
    W = np.random.randn(num_hidden, y.shape[0])
    for j in range(num_iterations):
        A = np.dot(X,V)
        B = sigmoid(A)
        C = np.dot(B,W)
        P = sigmoid(C)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdC = sigmoid(C) * (1-sigmoid(C))
        dLdC = dLdP * dPdC
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = dLdC * dCdB
        dBdA = sigmoid(A) * (1-sigmoid(A))
        dLdA = dLdB * dBdA
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        W -= dLdW
        V -= dLdV
    return V, W

def predict(X_new, V, W):
    A = np.dot(X_new,V)
    B = sigmoid(A)
    C = np.dot(B,W)
    P = sigmoid(C)
    return P

In [ ]:
def predict_complex_net(X_new, V, W):
    A = np.dot(X_new,V)
    B = sigmoid(A)
    C = np.dot(B,W)
    P = sigmoid(C)
    return P

In [ ]:
def plot_mesh_boundaries(V, W):
    h = .01
    x_min, x_max = X[:, 0].min(), X[:, 0].max()
    y_min, y_max = X[:, 1].min(), X[:, 1].max()
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    X_new = np.c_[xx.ravel(), yy.ravel()]
    Z = predict_complex_net(X_new, V, W)
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, cmap=plt.cm.coolwarm, alpha=0.8)
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.coolwarm, s=100)
    plt.xticks(np.arange(0,1.1,1.0))
    plt.yticks(np.arange(0,1.1,1.0))

In [ ]:
np.random.seed(3)
V, W = learn_complex_net(X, y)
plot_mesh_boundaries(V, W)

In [ ]:
X

In [ ]:
y

# Class

In [ ]:
class Layer(object):
    def _setup(self, input_shape, rng):
        """ Setup layer with parameters that are unknown at __init__(). """
        pass

    def fprop(self, input):
        """ Calculate layer output for given input (forward propagation). """
        raise NotImplementedError()

    def bprop(self, output_grad):
        """ Calculate input gradient. """
        raise NotImplementedError()

    def output_shape(self, input_shape):
        """ Calculate shape of this layer's output.
        input_shape[0] is the number of samples in the input.
        input_shape[1:] is the shape of the feature.
        """
        raise NotImplementedError()

In [ ]:
class Linear(Layer, ParamMixin):
    def __init__(self, n_out, weight_scale, weight_decay=0.0):
        self.n_out = n_out
        self.weight_scale = weight_scale

In [ ]:
class NeuralNetwork:
    def __init__(self, layers, rng=None):
        self.layers = layers
        if rng is None:
            rng = np.random.RandomState()
        self.rng = rng

In [ ]:
def _setup(self, X, Y):
    # Setup layers sequentially
    next_shape = X.shape
    for layer in self.layers:
        layer._setup(next_shape, self.rng)
        next_shape = layer.output_shape(next_shape)

In [ ]:
def predict(self, X):
    """ Calculate an output Y for the given input X. """
    X_next = X
    for layer in self.layers:
        X_next = layer.fprop(X_next)
    prediction = X_next
    return prediction

In [ ]:
def error(self, X, Y):
    """ Calculate error on the given data. """
    prediction = self.predict(X)
    loss = 0.5 * (prediction - Y) ** 2
    return loss

In [ ]:
def backprop(self, error):
    """ Calculate an output Y for the given input X. """
    # Back propagation of partial derivatives
    
    for layer in reversed(self.layers[:-1]):
        next_grad = layer.bprop(next_grad)

In [ ]:
l = [1,2]

In [ ]:
l.reverse()

In [ ]:
l

In [ ]:
def learn_simple_net(X, y):
    W = np.random.randn(3, 1)
    for i in range(50001):
        A = np.dot(X, W)
        P = sigmoid(A)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y - P)
        dPdA = sigmoid(A) * (1.0 - sigmoid(A))
        dLdA = dLdP * dPdA
        dAdW = X.T
        dLdW = np.dot(dAdW, dLdA)
        W -= 0.5 * dLdW
    return W

Way to think of this is: 

One layer:

Takes in X as input. It, as a layer, has weights, a way of combining those weights with the input X, and an activation function. 

It will have "fprop" as a class method.

And backprop. This method takes in "error" as an input and returns:
The input to the next level, which does not apply in this case since it is a one layer network.
The weight updates.

In [3]:
import numpy as np

In [ ]:
class NeuralNetwork:
    def __init__(self, layers):
        self.layers = layers
    
    def forwardpass(self, X):
        """ Calculate an output Y for the given input X. """
        X_next = X
        for layer in self.layers:
            X_next = layer.fprop(X_next)
        prediction = X_next
        return prediction
    
    def loss(self, prediction, Y):
        """ Calculate error on the given data. """
        loss = 0.5 * (Y - prediction) ** 2
        print -1.0 * (Y - prediction)
        return -1.0 * (Y - prediction)
    
    def backpropogate(self, loss):
        """ Calculate an output Y for the given input X. """
        loss_next = loss
        for layer in reversed(self.layers):
            loss_next = layer.bprop(loss_next)
        return loss
    
class Layer(object):
    def _setup(self, input_shape, rng):
        """ Setup layer with parameters that are unknown at __init__(). """
        pass

    def fprop(self, input):
        """ Calculate layer output for given input (forward propagation). """
        raise NotImplementedError()

    def bprop(self, output_grad):
        """ Calculate input gradient. """
        raise NotImplementedError()
        
def sigmoid(x, bprop=False):
    if bprop:
        s = sigmoid(x)
        return s*(1-s)
    else:
        return 1.0/(1.0+np.exp(-x))

        
class Linear(Layer):
    def __init__(self, n_in, n_out, input_layer=False):
        self.input_layer = input_layer
        self.W = np.random.randn(n_in, n_out)
        self.activation_function = sigmoid
        
    def fprop(self, layer_input):
        self.layer_input = layer_input
        self.activation_input = np.dot(layer_input, self.W)
        return self.activation_function(self.activation_input, bprop=False)

    def bprop(self, layer_grad):
        dPdAi = self.activation_function(self.activation_input, bprop=True)
        dLdAi = layer_grad * dPdAi
        dAodAi = self.layer_input.T
        W_new = self.W - np.dot(dAodAi, dLdAi)
        output_grad = np.dot(dLdAi, self.W.T)
        self.W = W_new      
        return output_grad

In [ ]:
# nn1 = NeuralNetwork(
#     layers=[
#         Linear(n_in=3,
#                n_out=1)
#         ]
#     )

In [ ]:
# X = np.array([  [0,0,1],
#                 [0,1,1],
#                 [1,0,1],
#                 [1,1,1] ])
    
# # output dataset            
# y = np.array([[0,0,1,1]]).T

In [ ]:
# for i in range(1000):
#     prediction = nn1.forwardpass(X)
#     print prediction
#     loss = nn1.loss(prediction, y)
#     nn1.backpropogate(loss)

In [ ]:
nn2 = NeuralNetwork(
    layers=[
        Linear(n_in=3,
               n_out=4,
               input_layer=True),
        Linear(n_in=4,
               n_out=1)
        ]
    )

In [7]:
import numpy as np
import random
randX = random.sample(range(1,9), 8)
mapping_dict = {1:[0,0,0],
               2:[0,0,1],
               3:[0,1,0],
               4:[0,1,1],
               5:[1,0,0],
               6:[1,0,1],
               7:[1,1,0],
               8:[1,1,1]}
X = []
for r in randX:
    X.append(mapping_dict[r])

y = []
randy = random.sample(range(1,9), 8)
for el in randy:
    if el % 2 == 0:
        y.append([0])
    else:
        y.append([1])

X = np.array(X)
y = np.array(y)

print "X: %s" % str(X)
print "y: %s" % str(y)

X: [[1 0 1]
 [0 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 1]
 [0 1 1]
 [0 0 1]
 [1 0 0]]
y: [[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]]


In [ ]:
def learn(X, y): 
    V = np.random.randn(X.shape[1], 4)
    W = np.random.randn(4, 1)
    for j in range(10000):
        A = np.dot(X,V)
        B = sigmoid(A)
        P = np.dot(B,W)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdW = B.T
        dLdW = np.dot(dPdW, dLdP)
        dPdB = W.T
        dLdB = np.dot(dLdP, dPdB)
        dBdA = sigmoid(A) * (1-sigmoid(A))
        dLdA = dLdB * dBdA
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        W -= dLdW
        V -= dLdV
    return V, W

In [ ]:
def predict_complex_net(X, V, W):
    A = np.dot(X,V)
    B = sigmoid(A)
    P = np.dot(B,W)
    return P

In [ ]:
V, W = learn_complex_net(X, y)
P = predict_complex_net(X, V, W)
P

In [ ]:
y

In [ ]:
np.set_printoptions(suppress=True)
def train_neural_net(net, X, y, epochs=10):
    for i in range(epochs):
        prediction = net.forwardpass(X)
        loss = net.loss(prediction, y)
        net.backpropogate(loss)
    return prediction

In [ ]:
train_neural_net(nn2, X, y)

In [ ]:
nn3 = NeuralNetwork(
    layers=[
        Linear(n_in=3,
               n_out=7,
               input_layer=True),
        Linear(n_in=7,
               n_out=4),
        Linear(n_in=4,
               n_out=1)
        ]
    )

In [ ]:
np.set_printoptions(suppress=True)
for i in range(10002):
    prediction = nn3.forwardpass(X)
    loss = nn3.loss(prediction, y)
    nn3.backpropogate(loss)
    if i % 10000 == 1:
        print prediction - y

In [1]:
from sklearn.datasets import fetch_mldata
import numpy as np
mnist = fetch_mldata('MNIST original')

In [2]:
data = mnist.data

In [3]:
data_clean = (data - data.min()) / (data.max() - data.min()) 

In [4]:
target = mnist.target

In [5]:
out = np.zeros((len(target), 10))
for i in range(len(target)):
    out[i][int(target[i])] = 1 

In [6]:
out

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [13]:
class NeuralNetwork:
    def __init__(self, layers):
        self.layers = layers
    
    def forwardpass(self, X):
        """ Calculate an output Y for the given input X. """
        X_next = X
        for layer in self.layers:
            X_next = layer.fprop(X_next)
        prediction = X_next
        return prediction
    
    def loss(self, prediction, Y):
        """ Calculate error on the given data. """
        loss = 0.5 * (Y - prediction) ** 2
        return -1.0 * (Y - prediction)
    
    def backpropogate(self, loss):
        """ Calculate an output Y for the given input X. """
        loss_next = loss
        for layer in reversed(self.layers):
            loss_next = layer.bprop(loss_next)
        return loss
    
class Layer(object):
    def _setup(self, input_shape, rng):
        """ Setup layer with parameters that are unknown at __init__(). """
        pass

    def fprop(self, input):
        """ Calculate layer output for given input (forward propagation). """
        raise NotImplementedError()

    def bprop(self, output_grad):
        """ Calculate input gradient. """
        raise NotImplementedError()
        
def sigmoid(x, bprop=False):
    if bprop:
        s = sigmoid(x)
        return s*(1-s)
    else:
        return 1.0/(1.0+np.exp(-x))

        
class Linear(Layer):
    def __init__(self, n_in, n_out, activation_function):
        self.W = np.random.normal(loc=0.0, scale=0.01, size=(n_in, n_out))
        self.activation_function = activation_function
        
    def fprop(self, layer_input):
        self.layer_input = layer_input
#         print self.layer_input.shape
        self.activation_input = np.dot(layer_input, self.W)
#         print self.activation_input.shape
        return self.activation_function(self.activation_input, bprop=False)

    def bprop(self, layer_grad):
        dPdAi = self.activation_function(self.activation_input, bprop=True)
        dLdAi = layer_grad * dPdAi
        dAodAi = self.layer_input.T
        W_new = self.W - 0.001 * np.dot(dAodAi, dLdAi)
        output_grad = np.dot(dLdAi, self.W.T)
        self.W = W_new      
        return output_grad

In [14]:
nn_mnist = NeuralNetwork(
    layers=[
        Linear(n_in=784,
               n_out=30,
               activation_function=sigmoid),
        Linear(n_in=30,
               n_out=20,
               activation_function=sigmoid),
        Linear(n_in=20,
               n_out=10,
               activation_function=sigmoid)
        ]
    )

In [15]:
def learn_neural_net(net, X, y):
    pred = net.forwardpass(X)
    loss = net.loss(pred, y)
    net.backpropogate(loss)
    return pred

In [16]:
for j in range(70000):
    i = np.random.randint(0,70000)
    X = np.array(data_clean[i], ndmin=2)
    y = np.array(out[i], ndmin=2)
    learn_neural_net(nn_mnist, X, y)

In [18]:
def learn(X, y):
    np.random.seed(2)
    V = np.random.randn(784, 30)
    W = np.random.randn(30, 10)
    for j in range(70000):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        A = np.dot(X,V)
        B = sigmoid(A)
        C = np.dot(B,W)
        P = sigmoid(C)
        sum_P = np.sum(P)
        L = 0.5 * (y - P) ** 2
#         if ( j % 10000) == 0:
#             print "Error:" + str(np.mean(np.abs(L)))
        dLdP = -1.0 * (y-P)
        dPdC = sigmoid(C) * (1-sigmoid(C))
        dLdC = dLdP * dPdC
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = np.dot(dLdC, dCdB)
        dBdA = sigmoid(A) * (1-sigmoid(A))
        dLdA = dLdB * dBdA
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        W -= dLdW
        V -= dLdV
    return V, W
        
def predict(X_new, V, W):
    A = np.dot(X_new,V)
    B = sigmoid(A)
    C = np.dot(B,W)
    P = sigmoid(C)
    return P

# X_new = [[1, 1, 1], [0, 1, 0]]

In [19]:
V, W = learn(data_clean, out)
P = predict(data_clean, V, W)

In [20]:
preds = []
for el in P:
    pred = np.argmax(el)
    preds.append(pred)

In [21]:
sum(preds == target) * 1.0 / len(preds)

0.36252857142857142

In [ ]:
def learn_complex_net(X, y, num_features, num_obs):
    np.random.seed(2)
    V = np.random.randn(num_features, 30)
    A_bias_init = np.random.normal(0, 1) 
    A_bias = np.full((num_obs, 1), A_bias_init)
    W = np.random.randn(30, 1)
    C_bias_init = np.random.normal(0, 1)
    C_bias = np.full((num_obs, 1), C_bias_init)
    for i in range(60000):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        A = np.dot(X,V)
        A_final = A + A_bias
        B = sigmoid(A_final)
        C = np.dot(B,W)
        C_final = C + C_bias
        P = sigmoid(C_final)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdC_final = sigmoid(C_final) * (1-sigmoid(C_final))
        dLdC_final = dLdP * dPdC_final
        dC_finaldC = 1
        dC_finalC_bias = 1
        dLdC_bias = dLdC_final * dC_finalC_bias
        dLdC = dLdC_final * dC_finaldC 
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = dLdC * dCdB
        dBdA_final = sigmoid(A_final) * (1-sigmoid(A_final))
        dLdA_final = dLdB * dBdA_final
        dA_finaldA = 1
        dA_finaldA_bias = 1
        dLdA_bias = dLdA_final * dA_finaldA_bias 
        dLdA = dLdA_final * dA_finaldA 
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        C_bias -= 0.5 * np.full((num_obs, 1), np.mean(dLdC_bias)) 
        A_bias -= 0.5 * np.full((num_obs, 1), np.mean(dLdA_bias)) 
        W -= 0.5 * dLdW
        V -= 0.5 * dLdV
    return V, W, np.mean(C_bias), np.mean(A_bias)

# V, W, C_bias, A_bias = learn_complex_net(X, y, 2, 4)

In [ ]:
for i in range(70000):
    learn_complex_net(data_clean, out, 784, 1)

In [90]:
class NeuralNetwork:
    def __init__(self, layers):
        self.layers = layers
    
    def forwardpass(self, X):
        """ Calculate an output Y for the given input X. """
        X_next = X
        for layer in self.layers:
            X_next = layer.fprop(X_next)
        prediction = X_next
        return prediction
    
    def loss(self, prediction, Y):
        """ Calculate error on the given data. """
        if len(Y.shape) == 1:
            Y = Y.reshape((Y.shape[0], 1))
        mse = 0.5 * (Y - prediction) ** 2
        loss = -1.0 * (Y - prediction)
        if len(loss.shape) == 1:
            loss = loss.reshape((1, 1))
        return loss
    
    def backpropogate(self, loss):
        """ Calculate an output Y for the given input X. """
        loss_next = loss
        for layer in reversed(self.layers):
            loss_next = layer.bprop(loss_next)
        return loss
    
class Layer(object):
    def _setup(self, input_shape, rng):
        """ Setup layer with parameters that are unknown at __init__(). """
        pass

    def fprop(self, input):
        """ Calculate layer output for given input (forward propagation). """
        raise NotImplementedError()

    def bprop(self, output_grad):
        """ Calculate input gradient. """
        raise NotImplementedError()
        
def sigmoid(x, bprop=False):
    if bprop:
        s = sigmoid(x)
        return s*(1-s)
    else:
        return 1.0/(1.0+np.exp(-x))
    
def linear(x, bprop=False):
    if bprop:
        return x
    else:
        return x

class Linear(Layer):
    def __init__(self, n_in, n_out, activation_function, lr=1):
        self.W = np.random.normal(loc=0.0, scale=1, size=(n_in, n_out))
        self.activation_function = activation_function
        self.lr = lr
        
    def fprop(self, layer_input):
        self.layer_input = np.array(layer_input, ndmin=2)
        self.activation_input = np.dot(layer_input, self.W)
        return self.activation_function(self.activation_input, bprop=False)

    def bprop(self, layer_grad):
        dPdAi = self.activation_function(self.activation_input, bprop=True)
        dLdAi = layer_grad * dPdAi
        dAodAi = self.layer_input.T
        W_update = np.dot(dAodAi, dLdAi)
        output_grad = np.dot(dLdAi, self.W.T) 
        self.W -= self.lr * W_update
        return output_grad

In [91]:
np.set_printoptions(suppress=True)
def train_neural_net(net, X, y):
    prediction = net.forwardpass(X)
    loss = net.loss(prediction, y)
    net.backpropogate(loss)
    return prediction    

In [78]:
accuracy_list = []
for iters in range(0, 100000, 5000):
    nn_mnist = NeuralNetwork(
    layers=[
        Linear(n_in=784,
               n_out=30,
               activation_function=sigmoid),
        Linear(n_in=30,
               n_out=10,
               activation_function=sigmoid)
        ]
    )
    for i in range(iters):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        train_neural_net(nn_mnist, X, y)
    preds = nn_mnist.forwardpass(data_clean)
    preds_list = []
    for el in preds:
        pred = np.argmax(el)
        preds_list.append(pred)
    accuracy = sum(preds_list == target) * 1.0 / len(preds_list)
    accuracy_list.append(accuracy)
    print iters
    print accuracy

0
0.105314285714
5000
0.199185714286
10000
0.203785714286
15000
0.266828571429
20000
0.291228571429
25000
0.270771428571
30000
0.3078
35000
0.318085714286
40000
0.330785714286
45000
0.3379
50000
0.337057142857
55000
0.320857142857
60000
0.361785714286
65000
0.349028571429
70000
0.336885714286
75000
0.353271428571
80000
0.369157142857
85000
0.354328571429
90000
0.349457142857
95000
0.351614285714


In [96]:
accuracy_list = []
for iters in range(0, 100000, 5000):
    nn_mnist = NeuralNetwork(
    layers=[
        Linear(n_in=784,
               n_out=25,
               activation_function=sigmoid),
        Linear(n_in=25,
               n_out=10,
               activation_function=sigmoid)
        ]
    )
    for i in range(iters):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        train_neural_net(nn_mnist, X, y)
    preds = nn_mnist.forwardpass(data_clean)
    preds_list = []
    for el in preds:
        pred = np.argmax(el)
        preds_list.append(pred)
    accuracy = sum(preds_list == target) * 1.0 / len(preds_list)
    accuracy_list.append(accuracy)
    print iters
    print accuracy

0
0.0971428571429
5000
0.168642857143
10000
0.211328571429
15000
0.2798
20000
0.291628571429
25000
0.297928571429
30000
0.300442857143
35000
0.295857142857
40000
0.3162
45000
0.348442857143
50000
0.350385714286
55000
0.346785714286
60000
0.343542857143
65000
0.360985714286
70000
0.336071428571
75000
0.345957142857
80000
0.354757142857
85000
0.353528571429
90000
0.368857142857
95000
0.356128571429


In [97]:
accuracy_list = []
for iters in range(0, 100000, 5000):
    nn_mnist = NeuralNetwork(
    layers=[
        Linear(n_in=784,
               n_out=20,
               activation_function=sigmoid),
        Linear(n_in=20,
               n_out=10,
               activation_function=sigmoid)
        ]
    )
    for i in range(iters):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        train_neural_net(nn_mnist, X, y)
    preds = nn_mnist.forwardpass(data_clean)
    preds_list = []
    for el in preds:
        pred = np.argmax(el)
        preds_list.append(pred)
    accuracy = sum(preds_list == target) * 1.0 / len(preds_list)
    accuracy_list.append(accuracy)
    print iters
    print accuracy

0
0.0968285714286
5000
0.154442857143
10000
0.232942857143
15000
0.264
20000
0.277557142857
25000
0.306285714286
30000
0.331085714286
35000
0.334942857143
40000
0.326185714286
45000
0.354328571429
50000
0.357
55000
0.350685714286
60000
0.357985714286
65000
0.3645
70000
0.349771428571
75000
0.371357142857
80000
0.361642857143
85000
0.3474
90000
0.3525
95000
0.372628571429


In [ ]:
accuracy_list = []
for iters in range(0, 100000, 5000):
    nn_mnist = NeuralNetwork(
    layers=[
        Linear(n_in=784,
               n_out=25,
               activation_function=sigmoid),
        Linear(n_in=25,
               n_out=10,
               activation_function=sigmoid)
        ]
    )
    for i in range(iters):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        train_neural_net(nn_mnist, X, y)
    preds = nn_mnist.forwardpass(data_clean)
    preds_list = []
    for el in preds:
        pred = np.argmax(el)
        preds_list.append(pred)
    accuracy = sum(preds_list == target) * 1.0 / len(preds_list)
    accuracy_list.append(accuracy)
    print iters
    print accuracy

In [94]:
accuracy_list = []
for iters in range(0, 100000, 5000):
    nn_mnist = NeuralNetwork(
        layers=[
            Linear(n_in=784,
                   n_out=30,
                   activation_function=sigmoid, 
                   lr = 0.5),
            Linear(n_in=30,
                   n_out=10,
                   activation_function=sigmoid,
                   lr=0.5)
            ]
        )
    for i in range(iters):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        train_neural_net(nn_mnist, X, y)
    preds = nn_mnist.forwardpass(data_clean)
    preds_list = []
    for el in preds:
        pred = np.argmax(el)
        preds_list.append(pred)
    accuracy = sum(preds_list == target) * 1.0 / len(preds_list)
    accuracy_list.append(accuracy)
    print iters
    print accuracy

0
0.0974142857143
5000
0.136828571429
10000
0.223857142857
15000
0.234642857143
20000
0.2807
25000
0.2809
30000
0.291314285714
35000
0.308071428571
40000
0.317228571429
45000
0.309457142857
50000
0.325085714286
55000
0.333714285714
60000
0.337042857143


KeyboardInterrupt: 

In [81]:
accuracy_list = []
for iters in range(0, 100000, 5000):
    nn_mnist = NeuralNetwork(
    layers=[
        Linear(n_in=784,
               n_out=30,
               activation_function=sigmoid),
        Linear(n_in=30,
               n_out=10,
               activation_function=sigmoid),
        Linear(n_in=10,
               n_out=10,
               activation_function=sigmoid),            
        ]
    )
    for i in range(iters):
        i = np.random.randint(0,70000)
        X = np.array(data_clean[i], ndmin=2)
        y = np.array(out[i], ndmin=2)
        train_neural_net(nn_mnist, X, y)
    preds = nn_mnist.forwardpass(data_clean)
    preds_list = []
    for el in preds:
        pred = np.argmax(el)
        preds_list.append(pred)
    accuracy = sum(preds_list == target) * 1.0 / len(preds_list)
    accuracy_list.append(accuracy)
    print iters
    print accuracy

0
0.0961428571429
5000
0.130114285714
10000
0.1617
15000
0.196971428571
20000
0.216314285714
25000
0.2265
30000
0.276185714286
35000
0.288042857143
40000
0.323342857143
45000
0.303385714286
50000
0.306814285714
55000
0.322928571429
60000
0.322642857143
65000
0.336585714286
70000
0.3277
75000
0.315414285714
80000
0.3385
85000
0.351128571429
90000
0.349414285714
95000
0.343685714286


In [82]:
accuracy_list

[0.096142857142857141,
 0.13011428571428571,
 0.16170000000000001,
 0.19697142857142858,
 0.21631428571428571,
 0.22650000000000001,
 0.27618571428571431,
 0.28804285714285716,
 0.32334285714285715,
 0.30338571428571426,
 0.30681428571428571,
 0.32292857142857145,
 0.32264285714285712,
 0.33658571428571427,
 0.32769999999999999,
 0.3154142857142857,
 0.33850000000000002,
 0.3511285714285714,
 0.34941428571428573,
 0.34368571428571426]

In [56]:
preds = nn_mnist.forwardpass(data_clean)
preds

array([[ 0.98598562,  0.00032984,  0.00302274, ...,  0.01935958,
         0.00154548,  0.00158472],
       [ 0.78680536,  0.24285232,  0.00795582, ...,  0.00455463,
         0.01069252,  0.0011276 ],
       [ 0.38486731,  0.00377702,  0.00880326, ...,  0.00074757,
         0.25050105,  0.00025249],
       ..., 
       [ 0.06552646,  0.00380538,  0.0000917 , ...,  0.00965458,
         0.00148867,  0.47006883],
       [ 0.01364895,  0.02672996,  0.0027566 , ...,  0.02580113,
         0.00509027,  0.01911549],
       [ 0.0365897 ,  0.00277089,  0.00086004, ...,  0.11624484,
         0.00679373,  0.32249287]])

In [59]:
preds_list = []
for el in preds:
    pred = np.argmax(el)
    preds_list.append(pred)

In [61]:
sum(preds_list == target) * 1.0 / len(preds_list)

0.35858571428571429

In [ ]:
out

In [ ]:
def learn_complex_net(X, y): 
    V = np.random.randn(X.shape[1], 4)
    W = np.random.randn(4, 1)
    for j in range(10000):
        A = np.dot(X,V)
        B = sigmoid(A)
        C = np.dot(B,W)
        P = sigmoid(C)
        L = 0.5 * (y - P) ** 2
        dLdP = -1.0 * (y-P)
        dPdC = sigmoid(C) * (1-sigmoid(C))
        dLdC = dLdP * dPdC
        dCdW = B.T
        dLdW = np.dot(dCdW, dLdC)
        dCdB = W.T
        dLdB = np.dot(dLdC, dCdB)
        dBdA = sigmoid(A) * (1-sigmoid(A))
        dLdA = dLdB * dBdA
        dAdV = X.T
        dLdV = np.dot(dAdV, dLdA)
        W -= dLdW
        V -= dLdV
    return V, W

In [ ]:
def predict_complex_net(X_new, V, W):
    A = np.dot(X_new,V)
    B = sigmoid(A)
    C = np.dot(B,W)
    P = sigmoid(C)
    return P

In [ ]:
V, W = learn_complex_net(X, y)
pred = predict_complex_net(X, V, W)
y - pred